### ISSUE TITLE
Do a Mock Trie Implementation

### ISSUE THREAD

**Issue by denizturkcapar** [cmsc22000-project-2018/spellcheck#10]
A Mock Trie Implementation that works with a few words to make sure that the spellcheck shell works correctly.

**Comment by firatciftci** [comment]
`compstr()` functions should be replaced with `strcmp()` found in `<string.h>`

**Comment by denizturkcapar** [comment]
Done

**Comment by denizturkcapar** [comment]
I wrote the implementations for the mock-trie. 

I first researched how the trie struct should be in order to cover what the dictionary functions need. 

I designed the trie struct in a way that the dictionary could utilize. 

I also thought about what functions were necessary and consulted the requirements of the dictionary in order to determine the functions I needed to write.
