### ISSUE TITLE
Shell Construction Discussion

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#13]

**Comment by firatciftci** [comment]
I think we need to divide this task into much smaller sub-tasks to make the overall picture clearer.

**Comment by jaepark98** [comment]
Sorry for not being clear in compartmentalizing roles within shell! This was just to mark that I would work on shell and parse_file per discussion on Monday. I'll update this issue as I push commits to my branch and divide into different tasks, which I'll specify in different issues.

See links for other parts of the shell that will be : [branch](https://github.com/cmsc22000-project-2018/spellcheck/tree/jaewan/shell)
