### ISSUE TITLE
Create README file

### ISSUE THREAD

**Issue by firatciftci** [cmsc22000-project-2018/spellcheck#19]
A README file will be created based on the design document located inside the wiki.

**Comment by jaepark98** [comment]
Would the content of the README file contain information on compilation as well?

**Comment by dwahme** [comment]
At a minimum, I'd say an overview of the project, (perhaps an example), a link to where they can easily find documentation (wiki), and instructions on how to build it.

**Comment by dwahme** [comment]
It's in the master branch now. See 0b3febdba0301c0333070ce483e827843e72c82d.

**Comment by firatciftci** [comment]
The README file was just a summarized version of the design document. It can, and probably will, be improved upon in the future, however.
