### ISSUE TITLE
Set up continuous integration for the 'dev' branch

### ISSUE THREAD

**Issue by firatciftci** [cmsc22000-project-2018/spellcheck#20]

**Comment by dwahme** [comment]
We should make sure that either criterion is installed or figure out a way to install it so we can run our tests and see the output automatically

**Comment by dwahme** [comment]
Criterion works now

https://travis-ci.org/cmsc22000-project-2018/spellcheck

**Comment by firatciftci** [comment]
CI set up, tests currently fail.

**Comment by dwahme** [comment]
Relevant commits:

aaa645fee5d8224f7fa8e65144c53fe29daba4b0
8ff220b207534b3722106a6641853bea2abb4de1
e88ba01cd37c8355af340e31aeb19b0304a0bfc7
3f845ad107194c061fb79cbd045e5408a4952548
bc26572cfdd1111ce7e7686bf7b8c808592a1c37
1d94f9f9c5e0e856557c7492d4d4c479938905d4
781dd09a21a4cff1d21588c51f154d3c2bd999da
c540db0104c0075c7dab1eef5bd9c5411aa24dcc
41c3a4dd73ab0084af003ad5e65207ca36fb0806
1b5619a271ff26d35bf9752d24c08114239225d0
1b1b526cce3ec90993737850639e23fb5a70283c
7df7fdd1a040e2b8159259805cd0b950ad913c9c
ab81b9368cd3a2c641fcbf6d6e5beaa481cc1e33
c3d6fb0622d2b0ffb5aea9f06de56192edfddb7c
