### ISSUE TITLE
Shell String Library Construction

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#22]
This is the shellstrings.c part of the shell library in the [branch](https://github.com/cmsc22000-project-2018/spellcheck/tree/jaewan/shell)

**Comment by firatciftci** [comment]
Something completely visual and not related to the implementation, but I feel like adding color to the shell strings can make the overall UI/UX more readable and clear. I can implement it if that is fine with you/everyone.

**Comment by jaepark98** [comment]
-commit at end of sprint 2 is [here](https://github.com/cmsc22000-project-2018/spellcheck/commit/c2d01b45bfce9e4dddae02eed8993c0feba0b855)

Due to many flaws, including failure to clearly document commits, new branch was opened. Start of new commit with descriptions of functions in parser.c file [here](https://github.com/cmsc22000-project-2018/spellcheck/commit/05e37c056680023d992d42639539f2aca07bca4b)

@firatciftci I think that would be great, could you wait though until I'm finished testing existing functions?

**Comment by jaepark98** [comment]
changed outputs to EXIT_SUCCESS

**Comment by jaepark98** [comment]
Final commit (before redesign, assigned to firat):
https://github.com/cmsc22000-project-2018/spellcheck/commit/b6b410d9c6c4823489d61b44d24b58d9ddb4f82c
