### ISSUE TITLE
implementing shell functionality

### ISSUE THREAD

**Issue by sarikam1** [cmsc22000-project-2018/spellcheck#26]
implementing display_suggestion on shell, i.e implementing replace_word, ignore_word and alternate_spelling

**Comment by firatciftci** [comment]
I have some shell functionality and color/layout implementation already done (I have it from the terminal screen recording for the wiki), so I will tidy up the shell code. I think we should debug the code first and then send a pull request to master (or dev).

**Comment by sarikam1** [comment]
Functions implemented:

//determines if a word is contained in the dict trie
int valid_word(char* word, dict_t *dict);
//hard coded suggestions for misspelled words
int generate_suggestions(char* word, dict_t* dict, char **suggestions);
//creates a string of underlines based on position of misspelled words
void underline_misspelled(char *tkn, char* underline);
void underline_correct_spelling(char *tkn, char* underline);
//creates an array of misspelled words
int add_to_badwords(char *badword, char** badwords);
//divides a line into individual tokens and processes them
int parse_string(char* string, dict_t *dict, char *underline, char** badwords);
//replaces incorrect words with users preferred one, based on suggestions
char* correct_line(char* line, char* old_word, char* new_word);

//initialises each element in array (that stores misspelled words in a line) to NULL
int initialize_badwords(char **badwords, int length);

//puts the aforementioned functions together
char* edit_interactive(char* line, dict_t* dict, int linenumber);
char** interactive_mode(char* filename, dict_t* dict, int* quit);
