### ISSUE TITLE
Write test functions for shellstrings

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#34]
shellstrings is a shell library. write testing functions

**Comment by jaepark98** [comment]
@firatciftci decided to split testing to make documentation for each more convenient, given that it'll be harder to do these collectively now that you're refactoring shellstrings.c and scfunctions.c will have to be changed before testing.

**Comment by firatciftci** [comment]
Decided that it is not really possible to test the shellstrings functions, as all of them are void returning functions with a collection of printf statements. Marking this issue as ungraded and closing it.

**Comment by firatciftci** [comment]
The latest PR has every commit for this issue.

See PR:
https://github.com/cmsc22000-project-2018/spellcheck/pull/92
