### ISSUE TITLE
Update Shell Makefiles and shell Travis

### ISSUE THREAD

**Issue by dwahme** [cmsc22000-project-2018/spellcheck#36]
Streamline compilation on the shell Makefiles and integrate with travis so that builds and tests happen automatically on the shell branch.

**Comment by jaepark98** [comment]
To do:
- add testing file sources
- update travis to test spellcheck with series of command line inputs

**Comment by dwahme** [comment]
All changes complete. Main Makefile include errors fixed, Makefile compilation streamlined, added test building to main Makefile, and updated travis to attempt to build spellcheck.

Relevant commits:
ad755f8f1c8f518bc84747ab4ea3632af9c95eb5
eef6f1a5fb50357d35f81c55e82acd5f6ffd58a6
3aa26ff3026ce7c61348a79214014cea46dbedba
d454e3ab20095b0df0f5d39aa66cdca42f5384b6
cc399d607639593d78e81007d9cc4e4ab101a342
ba4a621e6e0bd6c0310f36836a0cada26e363b8f
4cb73cb10ff62b8f25c8e2349060cde0ed79242f
