### ISSUE TITLE
Expand shellstrings library

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#60]
refactor main_functions.c, moving printf functions to shell string library

**Comment by jaepark98** [comment]
begun in old updated branch jae/shell: https://github.com/cmsc22000-project-2018/spellcheck/tree/jae/shell

**Comment by jaepark98** [comment]
Commit: d67bce54d9c7539429c2588c6d089760512db82a

**Comment by jaepark98** [comment]
Integration fails; see 
https://travis-ci.org/cmsc22000-project-2018/spellcheck/builds/381238654

**Comment by jaepark98** [comment]
Integrating word.c to ensure presentation on Monday is clean priority, moved to sprint 4

**Comment by firatciftci** [comment]
I have been working on this, check the firat/gui branch for ongoing development on the shellstrings. I would say leave this to me, as if we have two continuous development cycles on the same file, the code will get really messy. I am planning to PR my own work to the dev branch (and then hopefully the master branch) after the current PR is handled.

**Comment by jaepark98** [comment]
I think it's useful to separate out which types of changes to the shell string library needs to be done. Most of the work of moving printfs from main.c and main_functions.c is already done in jae/shell, and, additionally, editing has been done to clean batch mode as well in integrate/suggestions. I think the best way to go about this is to ensure that your work doesn't overlap with mine, and then to integrate into your branch if you want.
Either way, I think given that some development has already happened in jae/shell, this work should be considered separate and the exact implementation in the end should be discussed during merge before pull request. I'll update when my version of this is completed, which should be early this week unless I die from the CS154 project.

**Comment by jaepark98** [comment]
Aside from some printfs in main_function that are called concurrently with correct_line, and therefore are difficult to add to the shell library, all the functions have been moved.
Prepared to merge with firat/shell_gui: 10ed57aa0daa26d18de933264d958e10e012e362
@firatciftci
