### ISSUE TITLE
integration/word_suggestions 2: capitalization/error case handling for word.c

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#62]
The commit for this is in:
103d01ba3176e516de255ab69b611d4e5afd33d1

Note that while suggestions_list is called right now, cases of capitalization need to be handled; that is, since suggestions.c (eventually) should not differentiate between "She" and "she", capitalization needs to be decapitalized before suggestions is generated, and regenerated after . This and other error case handling should be implemented in word.c.

**Comment by firatciftci** [comment]
See commits:
https://github.com/cmsc22000-project-2018/spellcheck/commit/0206db03583360e10ca25109d0c74c6835fea662
https://github.com/cmsc22000-project-2018/spellcheck/commit/d7f6cfcdaabf74804945db929bb761f847926dfc
https://github.com/cmsc22000-project-2018/spellcheck/commit/6384a2c37de3bbeb989b0ace07d0f5e93a7d9df2
https://github.com/cmsc22000-project-2018/spellcheck/commit/ba516ddc99644283cf89c59d05d6bf6980b9cfcc
https://github.com/cmsc22000-project-2018/spellcheck/commit/21ac6d8aaa974fe4de84728720d21b1937c279bf

**Comment by firatciftci** [comment]
See PR:
https://github.com/cmsc22000-project-2018/spellcheck/pull/92
