### ISSUE TITLE
Exclusion of Color Strings for Testing

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#66]
@denizturkcapar 

See commits:
https://github.com/cmsc22000-project-2018/spellcheck/commit/c0e349ca4094c9e77b1585e32a94a3332823a661

**Comment by denizturkcapar** [comment]
See
https://github.com/cmsc22000-project-2018/spellcheck/commit/e0b8ef7fae73f03b263bce663c2f76aef72c1b49

**Comment by firatciftci** [comment]
See https://github.com/cmsc22000-project-2018/spellcheck/commit/95136ddad5a5c264f58083abecdcccea4d4fcf5d
