### ISSUE TITLE
Fixing shell library per meeting Week 8 Monday

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#69]
See https://github.com/cmsc22000-project-2018/spellcheck/issues/63

List:
 I. Interactive Mode
    Put suggested spellings first, instead of the delete line / enter / no replacement, which will be inserted after the suggestions after an empty line (A)
    Change the flags for the suggested spellings, such that “delete line” is d, no replacement is \n, etc. (Getting this to work without segfault is not..easy…) (A)
    (Think this was Firat's idea, initially) Maybe have a “Insert” option where the user can put their own options (A)
    Delete unnecessary lines, like “New sentence is”, “ (A)
    Change “File editing successful” to “Spellchecking done” or “Reached the End of the File” (A)
    Remove the exorbitant whitespaces in save_page (A)
    Solve the underlining error when the file reaches end of file (A)
    Write line and character (this is not going to be easy; keep in mind that if the line length is very long such that it does not fit in a given terminal, each line will be split to parse separately) (A).

II. Batch
    Write line and character under the “Line” section in the graph (line -> location, or line:char) (A)
    Don’t do the “Bye” message (A)

III. Quiet
    Print out lines if the file save destination has not been specified. (A)
    Assume interactive mode (may have misheard, plz verify if u remember) (A - might already be status quo)
    Note that command line inputs are single parameter + mode, and that the getopt function allows for an exception to be an output. (A)
    Change the command line input procedure (single parameter + modes) (A)

**Comment by jaepark98** [comment]
To be done in firat/jae/shell_gui

**Comment by jaepark98** [comment]
See https://github.com/cmsc22000-project-2018/spellcheck/commit/1469a7ca1ca935a7b8fbdca7e41c4347313ba3e5 for the following changes to interactive:

Put suggested spellings first, instead of the delete line / enter / no replacement, which will be inserted after the suggestions after an empty line (A)
Change the flags for the suggested spellings, such that “delete line” is d, no replacement is \n, etc. (Getting this to work without segfault is not..easy…) (A)
(Think this was Firat's idea, initially) Maybe have a “Insert” option where the user can put their own options (A)

**Comment by jaepark98** [comment]
Change “File editing successful” to “Spellchecking done” or “Reached the End of the File” (A)
Remove the exorbitant whitespaces in save_page (A)
Solve the underlining error when the file reaches end of file (A)
Write line and character (this is not going to be easy; keep in mind that if the line length is very long such that it does not fit in a given terminal, each line will be split to parse separately) (A).

all implemented in dev

**Comment by jaepark98** [comment]
Don’t do the “Bye” message (A)
Print out lines if the file save destination has not been specified. (A)
Assume interactive mode (may have misheard, plz verify if u remember) (A - might already be status quo)

complete

**Comment by jaepark98** [comment]
Remaining tasks:
-command line input change
-writing character number in batch mode

**Comment by jaepark98** [comment]
2586ae89dcec520465932b3cc350a568d5e348ff

**Comment by firatciftci** [comment]
See PR:
https://github.com/cmsc22000-project-2018/spellcheck/pull/92
