### ISSUE TITLE
Logging 

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#70]
-Enable command line flags (change)
-Printf control
-Remove colored strings in shellstring debug mode

**Comment by jaepark98** [comment]
first and third have been implemented so far. See latest version of dev
2586ae89dcec520465932b3cc350a568d5e348ff

**Comment by jaepark98** [comment]
27ffd6cdfbcbc6b59000223903c006b8906634b4

**Comment by firatciftci** [comment]
See PR:
https://github.com/cmsc22000-project-2018/spellcheck/pull/92
