### ISSUE TITLE
writing tests and documentation for new helper functions + fixing bugs

### ISSUE THREAD

**Issue by sarikam1** [cmsc22000-project-2018/spellcheck#76]
tests and documentation for the following:

/* removes any punctuation characters at the beginning of a string of alphabets */
int remove_prefix_punctuation(char *word);

/*removes any punctuation characters that trail a string of alphabets */
int remove_trailing_punctuation(char *word);

/* combines the aformenetioned functions:
removes trailing and prefix punctuation without modifying original word
/
char remove_punctuation(char *word);

**Comment by sarikam1** [comment]
commits include:

https://github.com/cmsc22000-project-2018/spellcheck/commit/920735e7c438429d38244283c122659292c73957

https://github.com/cmsc22000-project-2018/spellcheck/commit/e15372f4b3267bd5cc56b9db25706567e8e2563d

**Comment by jaepark98** [comment]
Additional commit: https://github.com/cmsc22000-project-2018/spellcheck/commit/bd1c66d6ec362346bc5684d0ba053191640aa56d
