### ISSUE TITLE
write functions to split lines according to max terminal char size without splitting over words

### ISSUE THREAD

**Issue by sarikam1** [cmsc22000-project-2018/spellcheck#77]

**Comment by jaepark98** [comment]
Not sure what a reasonable limit is; 80?

**Comment by sarikam1** [comment]
this was not actually pushed into dev in the interest of time, but here is the code I worked on:
https://docs.google.com/document/d/1NJljbD0x_qQIodDHeHzXOnAxsvypp4YB_iWz6-csapE/edit?usp=sharing
