### ISSUE TITLE
word.c - API integration

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#90]
`integration/suggestions` holds the most recent version of word.c.

Tasks:

- [x] Find a suitable English dictionary (as a .txt file).
- [x] Merge `dev` to `integration/suggestions` to enable API usage.

**Comment by firatciftci** [comment]
Found two files for the English dictionary from [this source](https://github.com/dwyl/english-words):

[This .txt file contains all English words (including numberic, alphanumeric, and punctuations.](https://raw.githubusercontent.com/dwyl/english-words/master/words.txt)

[This .txt file contains all English words that are alpha.](https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt)

**Comment by jaepark98** [comment]
API integration is done, but dict_suggestions is pending. to be resolved.
https://github.com/cmsc22000-project-2018/spellcheck/commit/51cc9112adec65fee8b4a9c5a915ebf382eab4ac
