### ISSUE TITLE
interactive mode changes

### ISSUE THREAD

**Issue by sarikam1** [cmsc22000-project-2018/spellcheck#94]
-underline only one word at a time for interactive mode
-allow user to select the max number of suggestions (and possibly max_edit distance?)

**Comment by jaepark98** [comment]
Both of theses changes have already been done. for the first, see
769c93dab5c20ba9aa6c864d9938cb9db34c497d
to
453b03d8663ec6890147b6a3ac3345309af62505

and the second, see
c441cb275e90390382c30600c347c34d3a9beaa2
